version: '3.8'

services:
  node:
    image: node:alpine
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    networks:
      - node-network
    working_dir: /app
    command: ["node","index.js"]

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - node-network

volumes:
  mongodb-data:

networks:
  node-network:
    driver: bridge